#version 450 core

layout(local_size_x = BLOCK_SIZE / 2) in;

layout(set = 0, binding = 0, std430) buffer Data {
    uint vals[];
};

layout(set = 0, binding = 1, std430) buffer BlockSums {
    uint block_sums[];
};

void main(void) {
    const uint prev_sum = block_sums[gl_WorkGroupID.x];
    vals[2 * gl_GlobalInvocationID.x] += prev_sum;
    vals[2 * gl_GlobalInvocationID.x + 1] += prev_sum;
}

