#version 450 core

#include "lru_cache_inputs.comp"

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

layout(set = 1, binding = 0, std140) uniform OldSize
{
    uint old_size;
};

void main(void)
{
    // Initialize each new empty slot
    slot_data[old_size + gl_GlobalInvocationID.x].age = 100000;
    slot_data[old_size + gl_GlobalInvocationID.x].available = 1;
    slot_data[old_size + gl_GlobalInvocationID.x].item_id = -1;
}

