#version 450 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std140) uniform VolumeParams
{
    uvec4 volume_dims;
    uvec4 padded_dims;
    vec4 volume_scale;

    uint max_bits;
    float isovalue;
    uint image_width;
};

layout(set = 0, binding = 1, std430) buffer RayIDs
{
    int ray_ids[];
};

void main(void)
{
    uint ray_index = gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * image_width;

    ray_ids[ray_index] = -1;
}


